Models/Departamento.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyTE.Models
{
    public class Departamento
    {
        [Column("idDepartamento")]
        public int IdDepartamento { get; set; }

        [Column("nomeDepartamento")]
        public string? NomeDepartamento { get; set; }

        // Propriedade de navegação para Usuarios
        public ICollection<Usuario>? Usuarios { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MyTe.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Horas.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyTE.Models
{
    public class Horas
    {
        [Column("idHoras")]
        public int IdHoras { get; set; }

        [Column("idUsuario")]
        public int IdUsuario { get; set; }

        [Column("codigoWbs")]
        public int CodigoWbs { get; set; }

        [Column("datas")]
        public DateTime Datas { get; set; }

        [Column("horas")]
        public TimeSpan HorasTrabalhadas { get; set; }

        // Propriedade de navegação para Usuario
        public Usuario? Usuario { get; set; }

        // Propriedade de navegação para Wbs
        public Wbs? Wbs { get; set; }
    }
}

Models/Localizacao.cs
namespace MyTe.Models
{
    public class Localizacao
    {
    }
}

Models/Login.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MyTE.Models
{
    public class Login
    {
        [Column("idLogin")]
        public int IdLogin { get; set; }

        [Column("email")]
        public string Email { get; set; }

        [Column("senha")]
        public string Senha { get; set; }

        [Column("idUsuario")]
        public int IdUsuario { get; set; }

        public Usuario? Usuario { get; set; }
    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyTE.Models
{
    public class Usuario
    {
        [Column("idUsuario")]
        public int IdUsuario { get; set; }

        [Column("nomeUsuario")]
        public string NomeUsuario { get; set; }

        [Column("dataNascimento")]
        public DateTime DataNascimento { get; set; }

        [Column("idDepartamento")]
        public int IdDepartamento { get; set; }

        [Column("tipo")]
        public int Tipo { get; set; }


        // Propriedade de navegação para Departamento
        public Departamento? Departamento { get; set; }

        // Propriedade de navegação para Horas
        public ICollection<Horas>? Horas { get; set; }

        // Propriedade de navegação para Login
        public ICollection<Login>? Logins { get; set; }
    }
}

Models/Wbs.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyTE.Models
{
    public class Wbs
    {
        [Column("codigoWbs")]
        public int CodigoWbs { get; set; }

        [Column("nomeWbs")]
        public string? NomeWbs { get; set; }

        [Column("descricaoWbs")]
        public string? DescricaoWbs { get; set; }
        // Propriedade de navegação para Horas
        // O ICollection<Horas> define um relacionamento de um-para-muitos entre a entidade Wbs e a entidade Horas. Isso significa que uma Wbs pode ter muitas entradas de Horas associadas a ela.
        public ICollection<Horas>? Horas { get; set; }

        // Propriedades de navegação permitem que você navegue nas relações entre entidades. Por exemplo, você pode acessar todas as horas registradas para uma determinada Wbs diretamente através dessa propriedade.
        // EF Core usa essas propriedades de navegação para carregar entidades relacionadas automaticamente (quando configurado para isso). Isso é útil para consultas e operações CRUD onde as entidades relacionadas precisam ser acessadas ou manipuladas.

    }
}

Controllers/AdminDepartamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{
    public class AdminDepartamentoController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Update()
        {
            return View();
        }
    }
}

Controllers/AdminLocalizacaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{
    public class AdminLocalizacaoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/AdminPerfilController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{
    public class AdminPerfilController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/AdminUsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{
    public class AdminUsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Update()
        {
            return View();
        }

        public IActionResult Delete()
        {
            return View();
        }

        public IActionResult Read()
        {
            return View();
        }
    }
}

Controllers/AdminWbsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{
    public class AdminWbsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyTe.Models;
using System.Diagnostics;

namespace MyTe.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserHorasController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{
    public class UserHorasController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Update()
        {
            return View();
        }
    }
}

Controllers/UserLocalizacaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers
{

    public class UserLocalizacaoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UserPerfilController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers

{
    public class UserPerfilController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UserWbsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTe.Controllers

{
    public class UserWbsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }

    }
}

Views/AdminDepartamento/Create.cshtml
@{
    ViewData["Title"] = "Create Department";

}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/EditingDepartment.css">

</head>
<body>
    <!-- Mudança no título -->
    <h1 class="title">Creating Department</h1>


    <div class="container form-container">
        <!-- CADA LINHA CONSEGUE CARREGAR 2 DIVS -->
        <!-- PRIMEIRA LINHA/ROW -->
        <div class="form-row">

            <div class="form-column">
                <label for="name">Name:</label>
                <input type="text" id="name" class="form-control" placeholder="RH">
            </div>


        </div>


        <!-- Mudança na localização do botão Save -->
    </div>
    <div class="form-row justify-content-end">
        <button type="button" class="btn btn-save">Save</button>
    </div>


</body>

</html>

Views/AdminDepartamento/Index.cshtml
@{
	ViewData["Title"] = "Departament List";

}


<meta name="viewport" content="width-device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/css/GerenciarUsuarios.css">

<div class="container-conteudo">

	<h2 class="work-sans">Departament List</h2>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Department Name</th>
				<th scope="col">Manager email</th>
				<th scope="col">Edit </th>
				<th scope="col">Active</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row">1</th>
				<td>Marketing</td>
				<td>annie@gmail.com</td>
				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">2</th>
				<td>Negócios</td>
				<td>Bianca@gmail.com</td>
				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">3</th>
				<td>Tech</td>
				<td>Fulano@gmail.com</td>
				<td>
					<img role="button" class="mini-icons" src="~/images/pencil.svg" />
				</td>
				<td>

					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			</div>
		</tbody>
	</table>

</div>
<div class="btn-position">
	<button>New Departament</button>
</div>

Views/AdminDepartamento/Update.cshtml
@{
    ViewData["Title"] = "Editing Department";

}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/EditingDepartment.css">

</head>
<body>
    <!-- Mudança no título -->
    <h1 class="title">Editing Department</h1>


    <div class="container form-container">
        <!-- CADA LINHA CONSEGUE CARREGAR 2 DIVS -->
        <!-- PRIMEIRA LINHA/ROW -->
        <div class="form-row">

            <div class="form-column">
                <label for="name">Name:</label>
                <input type="text" id="name" class="form-control" placeholder="Marketing">
            </div>


        </div>


        <!-- Mudança na localização do botão Save -->
    </div>
    <div class="form-row justify-content-end">
        <button type="button" class="btn btn-save">Save</button>
    </div>


</body>

</html>

Views/AdminLocalizacao/Index.cshtml
@{
	ViewData["Title"] = "Location List";

}


<meta name="viewport" content="width-device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/css/GerenciarUsuarios.css">

<div class="container-conteudo">

	<h2 class="work-sans">Location List</h2>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Location name</th>
				<th scope="col">Code</th>
				<th scope="col">Edit</th>
				<th scope="col">Active</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row">1</th>
				<td>São Paulo</td>
				<td>SP</td>

				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">2</th>
				<td>Recife</td>
				<td>RE</td>

				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">3</th>
				<td>Porto Aletre</td>
				<td>PA</td>

				<td>
					<img role="button" class="mini-icons" src="~/images/pencil.svg" />
				</td>
				<td>

					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
		</tbody>
	</table>

</div>
<div class="btn-position">
	<button>
		Add New Location
	</button>
</div>

Views/AdminPerfil/Index.cshtml
@{
	ViewData["Title"] = "Profile";

}

<meta name="viewport" content="width-device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/css/Profile.css">

<h1  class="work-sans">Profile</h1>

<div class="conteiner-conteudo">
	<div class="silhueta-img"> 
		<img  src="~/images/img-perfil.jpg" alt="silhueta de perfil" width="200px" height="200px" />
	</div>
	<div class="conteudo">
		<div class="sub-div">
			<p class="bold">Name</p>
			<span>Fulano de tal</span>
		</div>

		<div class="sub-div">
			<p class="bold">E-mail</p>
			<span>fulanodetal@gmail.com</span>
		</div>
	</div>


	<div class="conteudo">
		<div class="sub-div">
			<p class="bold">Date of Birth</p>
			<span>18/04/2000</span>
		</div>

		<div class="sub-div">
			<p class="bold">Departament</p>
			<span>Marketing</span>
		</div>

	</div>

</div>

<div class="btn-position">
	
		<button>Admin Access</button>

	
</div>

Views/AdminUsuario/Create.cshtml
@{
    ViewData["Title"] = "Adding new Employee";
}

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/AddNewEmployee.css">

<div class="container-conteudo">
    <!-- Mudança no título -->
    <h2 class="work-sans">Adding new Employee</h2>


    <div class="container form-container">
        <div class="form-row">
            <div class="form-column">
                <label for="name">Name:</label>
                <input type="text" id="name" class="form-control" placeholder="Enter name">
            </div>
            <div class="form-column">
                <label for="birthdate">Birthdate:</label>
                <input type="date" id="birthdate" class="form-control">
            </div>
        </div>
        <div class="form-row">
            <div class="form-column">
                <label for="email">Email:</label>
                <input type="email" id="email" class="form-control" placeholder="Enter email">
            </div>
            <div class="form-column">
                <label for="password">Password:</label>
                <input type="password" id="password" class="form-control" placeholder="Enter password">
            </div>
        </div>
        <div class="form-row">
            <div class="form-column">
                <label for="department">Department:</label>
                <select id="department" class="form-control">
                    <option value="dev">Development</option>
                    <option value="hr">Human Resources</option>
                    <option value="sales">Sales</option>
                </select>
            </div>
            <div class="form-column">
                <label for="type">Type:</label>
                <select id="type" class="form-control">
                    <option value="user">User</option>
                    <option value="admin">Administrator</option>
                </select>
            </div>
        </div>
        <!-- Mudança na localização do botão Save -->
    </div>
</div>
    <div class="form-row justify-content-end">
        <button>Save</button>
    </div>

Views/AdminUsuario/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/AdminUsuario/EditingWBS.cshtml
@{
    ViewData["Title"] = "Editing WBS";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/EditingWBS.css">
</head>
<body>
    <!-- Mudança no título -->
    <h1 class="title">Editing WBS</h1>

    <div class="container form-container">
        <div class="form-row">
            <div class="form-column">
                <label for="name">Name:</label>
                <input type="text" id="name" class="form-control" placeholder="Enter name">
            </div>
            <div class="form-column">
                <label for="code">Code:</label>
                <input type="text" id="code" class="form-control" placeholder="Enter code">
            </div>
        </div>
        <div class="form-row">
            <div class="form-column">
                <label for="description">Description:</label>
                <textarea id="description" class="form-control" placeholder="Enter description"></textarea>
            </div>
        </div>
    </div>
</body>
</html>

Views/AdminUsuario/Index.cshtml
@{
	ViewData["Title"] = "Lista de Funcionários";
}

<meta name="viewport" content="width-device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/css/GerenciarUsuarios.css">

<div class="container-conteudo">

	<h2 class="work-sans">Employee's List</h2>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Name</th>
				<th scope="col">E-mail</th>
				<th scope="col">Department</th>
				<th scope="col">Type</th>
				<th scope="col">Edit </th>
				<th scope="col">Active</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row">1</th>
				<td>Annie Santana</td>
				<td>annie@gmail.com</td>
				<td>Dev</td>
				<td>Usuário</td>
				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">2</th>
				<td>Bianca Uno</td>
				<td>Bianca@gmail.com</td>
				<td>dev</td>
				<td>Usuário</td>
				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">3</th>
				<td>Fulano</td>
				<td>Fulano@gmail.com</td>
				<td>RH</td>
				<td>Admin</td>
				<td>
					<img role="button" class="mini-icons" src="~/images/pencil.svg" />
				</td>
				<td>

					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
		</tbody>
	</table>

</div>
<div class="btn-position">
	<button>Add Employee</button>
</div>

Views/AdminUsuario/Read.cshtml
@{
	ViewData["Title"] = "GerenciarUsuarios";

}


<meta name="viewport" content="width-device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/css/GerenciarUsuarios.css">

<div class="container-conteudo">

	<h2 class="work-sans">Employees List</h2>

	<table class="table">
		<thead>
			<tr>
				<th scope="col"></th>
				<th scope="col">Name</th>
				<th scope="col">E-mail</th>
				<th scope="col">Department</th>
				<th scope="col">Type</th>
				<th scope="col">Edit </th>
				<th scope="col">Active</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row">1</th>
				<td>Annie Santana</td>
				<td>annie@gmail.com</td>
				<td>Dev</td>
				<td>Usuário</td>
				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">2</th>
				<td>Bianca Uno</td>
				<td>Bianca@gmail.com</td>
				<td>dev</td>
				<td>Usuário</td>
				<td>
					<a> <img role="button" class="mini-icons" src="~/images/pencil.svg" /> </a>
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
			<tr>
				<th scope="row">3</th>
				<td>Fulano</td>
				<td>Fulano@gmail.com</td>
				<td>RH</td>
				<td>Admin</td>
				<td>
					<img role="button" class="mini-icons" src="~/images/pencil.svg" />
				</td>
				<td>
					<div class="form-check form-switch">
						<input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
						<label class="form-check-label" for="flexSwitchCheckChecked"></label>
					</div>
				</td>
			</tr>
		</tbody>
	</table>

</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-start">
	<a class="btn btn-primary" role="button">
		Add Employee
	</a>
</div>

Views/AdminUsuario/Update.cshtml
@{
    ViewData["Title"] = "Editing Employee";
}

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Update.css">

<div class="container-conteudo">
    <!-- Mudança no título -->
    <h2 class="work-sans">Editing Employee</h2>


    <div class="container form-container">
        <div class="form-row">
            <div class="form-column">
                <label for="name">Name:</label>
                <input type="text" id="name" class="form-control" placeholder="Enter name">
            </div>
            <div class="form-column">
                <label for="birthdate">Birthdate:</label>
                <input type="date" id="birthdate" class="form-control">
            </div>
        </div>
        <div class="form-row">
            <div class="form-column">
                <label for="email">Email:</label>
                <input type="email" id="email" class="form-control" placeholder="Enter email">
            </div>
            <div class="form-column">
                <label for="password">Password:</label>
                <input type="password" id="password" class="form-control" placeholder="Enter password">
            </div>
        </div>
        <div class="form-row">
            <div class="form-column">
                <label for="department">Department:</label>
                <select id="department" class="form-control">
                    <option value="dev">Development</option>
                    <option value="hr">Human Resources</option>
                    <option value="sales">Sales</option>
                </select>
            </div>
            <div class="form-column">
                <label for="type">Type:</label>
                <select id="type" class="form-control">
                    <option value="user">User</option>
                    <option value="admin">Administrator</option>
                </select>
            </div>
        </div>
        <!-- Mudança na localização do botão Save -->
    </div>
</div>
    <div class="form-row justify-content-end">
        <button>Save</button>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyTe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyTe.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar-transparent border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mytelogo-render.png" alt="Logo" width="100px" class="logo-myte">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav w-100 nav-fill">
                        <li class="nav-item position-relative">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminUsuario" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminWbs" asp-action="Index">WBS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminLocalizacao" asp-action="Index">Location</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminDepartamento" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="Index">Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminPerfil" asp-action="Index">Profile</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyTe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            // Adiciona a classe 'active-bar' à âncora da página ativa
            $('.nav-item').each(function () {
                if ($(this).find('a').attr('href') == window.location.pathname) {
                    $(this).find('a').addClass('active-bar');
                }
            });
        });
    </script>
</body>
</html>

Views/UserHoras/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/UserHoras/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}